import type { Metadata } from "next";
import { Amarante  } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

//NeueMachina-Ultrabold

// const neueMachina = localFont({
//   src: './NeueMachina-Ultrabold.otf',
//   style: 'ultrabold',
// })

const amarante = Amarante({
  weight: "400",
  subsets: ["latin"],

  variable: "--font-amarante",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${amarante.className} ${amarante.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
